// <auto-generated />
namespace memberSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_Account_view_modea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_Account_view_modea));
        
        string IMigrationMetadata.Id
        {
            get { return "201603182028348_changed_Account_view_modea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
