// <auto-generated />
namespace memberSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeduseridtojobposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeduseridtojobposts));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221417496_added user id to job posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
